// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAGOkQe8d5zOvpKcfd016g0fyyLrc2w08',
    appId: '1:827124946935:web:a766f8acc7d03c613b00f2',
    messagingSenderId: '827124946935',
    projectId: 'educlass-7b83c',
    authDomain: 'educlass-7b83c.firebaseapp.com',
    storageBucket: 'educlass-7b83c.firebasestorage.app',
    measurementId: 'G-NK4J5NVSGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskwm4GVELKU6Tt6H2mjyigUVJqe2lkwI',
    appId: '1:827124946935:android:f75299e228d91b793b00f2',
    messagingSenderId: '827124946935',
    projectId: 'educlass-7b83c',
    storageBucket: 'educlass-7b83c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKAe07I1iB2uwpq9d-8nid0m4ChAnXAS0',
    appId: '1:827124946935:ios:e8e63aa9698a74ad3b00f2',
    messagingSenderId: '827124946935',
    projectId: 'educlass-7b83c',
    storageBucket: 'educlass-7b83c.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );
}
